# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Radio Title')),
                ('url', models.TextField(default='', verbose_name='Radio Url')),
            ],
        ),
        migrations.CreateModel(
            name='SourceUri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Uri path')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='radio.Radio')),
            ],
        ),
    ]
